input1 = input()
input1 = input1.split()
A = float(input1[0])
B = float(input1[1])
C = float(input1[2])
TRIANGULO = ((1.0 / 2) * A * C)
CIRCULO = (3.14159 * (C**2))
TRAPEZIO = (((A + B) / 2) * C)
QUADRADO =  (B * B)
RETANGULO = (A*B)
print("TRIANGULO: %.3f"%TRIANGULO)
print("CIRCULO: %.3f"%CIRCULO)
print("TRAPEZIO: %.3f"%TRAPEZIO)
print("QUADRADO: %.3f"%QUADRADO)
print("RETANGULO: %.3f"%RETANGULO)
